# Site settings
name: Samp's Blog
email: 31461013@qq.com
author: Samp
url: http://sampmiao.github.io
resume_site: http://sampmiao.github.io/
github: https://github.com/sampmiao
baseurl: ''



#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']


github_username: sampmiao

# Build settings
markdown: kramdown
highlighter: rouge

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : sampmiao
    #disqus :
    #    short_name : sampmiao
    #facebook : 
    #   appid : sampmiao
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light

# Jekyll themes http://jekyllthemes.org/page3/
# LessOrMore Theme https://github.com/luoyan35714/LessOrMore